maki/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
import debug_toolbar
from maki import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/', include('shop.urls')),

]
if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [path(r"__debug__/", include(debug_toolbar.urls))]

urlpatterns += [
    path(r'accounts/', include('django.contrib.auth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

shop/urls.py
from django.conf.urls.static import static

from maki import settings
from . import views
from django.urls import include, path

app_name = 'shop'

urlpatterns = [path('homepage/', views.HomePage.as_view(), name='homeview'),
               path('product/<int:pk>', views.ProductDetail.as_view(), name='product-detail'),
               path('save_feedback/', views.save_feedback, name='save-feedback'),
               path('add_to_basket/<int:pk>', views.add_to_basket, name='add-to-basket'),
               path('add_to_basket_from_details/<int:pk>', views.add_to_basket_from_details, name='add-to-basket-from-details'),
               path('del_good_from_basket', views.del_good_from_basket, name='del-good-from-basket'),
               path('basket/', views.ProductBasket.as_view(), name='basket'),
               path('user_registration/', views.UserRegistration.as_view(), name='user-registration'),
               path('product_order/', views.ProductOrder.as_view(), name='product-order'),

               ]

shop/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
from django.forms import ModelForm


class Product(models.Model):
    choices = (
        ('bouquet', 'Bouquet'),
        ('present', 'Present'),
        ('composition', 'Composition'),)
    name = models.CharField(max_length=200)
    quantity = models.IntegerField()
    price = models.FloatField()
    description = models.TextField(max_length=1000)
    available = models.BooleanField(default=False)
    category = models.CharField(max_length=1, choices=choices, default='b')
    img_1 = models.ImageField(upload_to='products/img')
    img_2 = models.ImageField(upload_to='shop/static/img/products', blank=True)
    img_3 = models.ImageField(upload_to='shop/static/img/products', blank=True)
    img_4 = models.ImageField(upload_to='shop/static/img/products', blank=True)
    label = models.CharField(max_length=10,
                             choices=(
                                 ('item_new', 'n'), ('item_hit', 'h'), ('item_action', 'a'),
                                 (' ', '')),
                             default=' ')

    def __str__(self):
        return self.name


class Feedback(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    text = models.TextField(max_length=300)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    date = models.DateTimeField(auto_now=True)
    rating = models.IntegerField(choices=((1, 1), (2, 2), (3, 3), (4, 4), (5, 5)), default=5)

    class Meta:
        ordering = ['date']


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    order_date = models.DateTimeField(auto_now=True)
    payed = models.BooleanField(default=False)
    send = models.BooleanField(default=False)
    resive = models.BooleanField(default=False)
    order_sum = models.FloatField()
    recipient_phone = models.CharField(max_length=13)
    recipient_card = models.CharField(max_length=13)
    recipient_first_name = models.CharField(max_length=13)
    recipient_last_name = models.CharField(max_length=13)
    recipient_surname = models.CharField(max_length=13)
    recipient_city_address = models.CharField(max_length=13)
    recipient_local_address = models.CharField(max_length=13)
    add_free_message_card = models.BooleanField(max_length=13)
    free_message_card_text = models.TextField(max_length=100)
    delivery_datetime = models.DateTimeField()


class OrderForm(ModelForm):

    class Meta:
        model = Order
        exclude = ['order_date', 'send', 'payed']


class GoodsInOrder(models.Model):
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True, blank=True)
    good = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    payment = models.CharField(choices=(('online', 'online'), ('cash_on', 'cash_on')), max_length=15, default='cash_on')

shop/forms.py
from django import forms
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ValidationError

from django.contrib.auth.models import User

from shop.models import GoodsInOrder


class RegisterUserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    confirm_password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email']

    def valid_password(self):
        valid = self.changed_data
        if valid['password'] != valid['confirm_password']:
            raise ValidationError('Паролі не співпадають')
        return valid['password']


class AddToBasketFromDetails(forms.ModelForm):
    class Meta:
        model = GoodsInOrder
        fields = ['quantity', 'order']

shop/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.sites.shortcuts import get_current_site
from django.http import HttpResponseForbidden
from django.shortcuts import render, render_to_response, redirect
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.views import generic

from shop.forms import RegisterUserForm, AddToBasketFromDetails
from .models import *
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


# Create your views here.
class TopProductCookiesMixin:

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=None, **kwargs)
        quantity = 0
        sum = 0
        for item in self.request.session.keys():
            if 'good_' in item:
                q = int(self.request.session.get(item))
                id = int(item[5:])
                try:
                    good = Product.objects.get(pk=id)
                    price = good.price
                    quantity += q
                    sum += q * price
                except:
                    pass

        context['total_quantity'] = quantity
        context['sum'] = sum
        context['order'] = False
        return context


class HomePage(TopProductCookiesMixin, generic.ListView):
    model = Product
    paginate_by = 4

    def listing(self):
        product_list = Product.objects.all()
        paginator = Paginator(product_list, 4)  # Show 4 contacts per page

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(HomePage, self).get_context_data(**kwargs)
        quantity_goods = 0
        total_sum = 0
        for item in self.request.session.keys():
            if 'good_' in item:
                q = int(self.request.session.get(item))
                id_good = int(item[5:])
                try:
                    good = Product.objects.get(pk=id_good)
                    quantity_goods += q
                    total_sum += q * good.price
                except:
                    pass

        context['total_quantity'] = quantity_goods
        context['total_sum'] = total_sum
        return context


class ProductDetail(TopProductCookiesMixin, generic.DetailView):
    model = Product

    def get_context_data(self, *, object_list=None, **kwargs):
        if self.request.GET.get('order_quantity'):
            print("GEEET")
            self.request.session['good_' + str(self.kwargs['pk'])] = int(self.request.GET.get('order_quantity'))
        context = super().get_context_data(object_list=None, **kwargs)
        context['quantity'] = self.request.session.get('good_' + str(self.kwargs['pk']), 1)
        return context

    # def get_queryset(self):
    #     result = super().get_queryset()
    #     result2 = Product.objects.all()
    #     return result2


def add_to_basket_from_details(request, pk):
    print(request.GET.get('order_quantity'))
    good = 'good_' + str(pk)
    quantity = request.session.get(good, 0)
    # request.session[good] = quantity + value_quantity


def save_feedback(request):
    if request.POST:
        # print(request.POST)
        feedback = Feedback()
        feedback.user_id = int(request.POST['user_id'])
        feedback.product_id = int(request.POST['product_id'])
        feedback.text = request.POST['text']

        if not Feedback.objects.filter(text__contains=request.POST['text']):
            feedback.save()

        return redirect(to=request.POST['url'])
    else:
        redirect(to='/')


def add_to_basket(request, pk):
    good = 'good_' + str(pk)
    quantity = request.session.get(good, 0)
    request.session[good] = quantity + 1

    for item in request.session.keys():
        print(item, '=', request.session.get(item))
    return redirect(to='/shop/homepage/')


def del_good_from_basket(request):
    request.session.pop(request.GET.get('remove'))
    return redirect('shop:basket')


class ProductBasket(generic.TemplateView, TopProductCookiesMixin):
    template_name = 'basket.html'

    def get_context_data(self, **kwargs):

        context = super(ProductBasket, self).get_context_data(**kwargs)
        total_sum = 0
        goods = []

        for item in self.request.session.keys():
            if 'good_' not in item:
                continue
            quantity_goods = int(self.request.session.get(item))
            context['total_quantity'] = quantity_goods

            try:
                good = Product.objects.get(pk=int(item[5:]))
                summ = quantity_goods * good.price
                total_sum += summ
                goods.append((good, int(self.request.session.get(item)), summ))
            except:
                pass
        context['goods'] = goods
        context['total_sum'] = total_sum
        context['order'] = True
        return context


class ProductOrder(TopProductCookiesMixin, LoginRequiredMixin, generic.CreateView):
    template_name = 'product_order.html'
    model = Order
    form_class = OrderForm
    success_url = 'shop:product_list'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['order'] = True

        return context

    def form_valid(self, form):
        print(form.cleaned_data)

    def form_invalid(self, form):
        print("Form invalid")
        print(form.cleaned_data)

    # def save_to_database(self):


class UserRegistration(generic.CreateView):
    form_class = RegisterUserForm
    template_name = 'registration/user_registration.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return HttpResponseForbidden()

        return super(UserRegistration, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        # print('form valid')
        user = form.save(commit=False)
        user.set_password(form.cleaned_data['password'])
        user.save()
        # print("_______", user)
        # login(request=self.request, user=user)
        # print("_______222222", user)
        # current_site = get_current_site(self.request)
        # subject = 'Activation of your account'
        # message = render_to_string('blog/acc_activate_email.html', {'user': user,
        #                                                             'domain': current_site.domain,
        #                                                             'uid': urlsafe_base64_encode(
        #                                                                 force_bytes(user.pk)).decode(),
        #                                                             'token': account_activation_token.make_token(
        #                                                                 user)})
        # to_email = form.cleaned_data['email']
        #
        # email = EmailMessage(subject, message, to=[to_email])
        # email.send()
        # messages.success(self.request, 'Please confirm account by your e-mail.')

        return redirect(to='/shop/homepage/')

shop/templates/base_template.html
<html lang="ru">
<head>
    {% block title %}{% endblock %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/fonts.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/jquery-ui.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/jquery-ui.structure.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/jquery-ui.theme.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/lightslider.min.css' %}">

    <link rel="stylesheet" type="text/css" href="{% static 'css/main.min.css' %}">
</head>
<body>
<header class="header">
    <div class="header__top">
        <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
                <li><a href="{% url 'logout' %}?next={{ request.path }}">Logout</a></li>
            {% else %}
                <li><a href="{% url 'shop:user-registration' %}"><span class="glyphicon glyphicon-user"></span> Sign Up</a>
                </li>
                <li><a>
                    <span class="glyphicon glyphicon-user"></span>Have an Account?
                    <form method="post" action={% url 'login' %}>
                        {% csrf_token %}
                        <label> Name: </label>
                        <input type="text" name="username">
                        <label> Password: </label>
                        <input type="password" name="password">
                        <input type="submit" name="Login">
                    </form>
                </a>

                </li>



            {% endif %}
        </ul>

        <div class="wrapper">
            <div class="header__search">
                <form class="search_form" method="get" action="shop/product_list.html"><input class="search__field"
                                                                                              type="search"
                                                                                              placeholder="Что вы ищите?"
                                                                                              name="date_search">
                    <a class="search__btn" href="#"></a>
                </form>

            </div>

            <div class="toggle__menu">
                <span class="toggle__top"></span>
                <span class="toggle__mid"></span>
                <span class="toggle__bot"></span>
            </div>

            <nav class="main__menu">
                <ul>
                    <li><a href="#">Доставка</a></li>
                    <li><a href="#">Оплата</a></li>
                    <li><a href="#">Гарантии</a></li>
                    <li><a href="#">Контакты</a></li>
                    <li><a href="#">Статус заказа</a></li>
                </ul>
            </nav>
        </div>
    </div>
    <div class="header__mid">
        <div class="wrapper">
            <div class="col_pull clearfix">
                <div class="col_x3">
                    <div class="header__logo">
                        <a href="{% url 'shop:homeview' %}">
                            <img src="{% static 'img/logo.png' %}" alt="logo">
                            <span class="logo__text">Интернет-магазин цветов</span>
                        </a>
                    </div>
                </div>
                <div class="col_x3">
                    <div class="header__contact">
                        <div class="header__adress">г. <span class="text_bold">Челябинск,</span> ул. Воровского, 30A
                        </div>
                        <div class="header__email">e-mail: buket@mail.ru</div>
                        <div class="header__phone">
                            <a href="tel:83515672146"><span class="phone_pink">8(351)</span> 567 21 46</a>
                        </div>
                    </div>
                </div>
                {% if not order %}
                    {% block basket %}
                        <div class="col_x3">
                            <div class="header__order">
                                <a href="{% url 'shop:basket' %}" class="order__btn">Корзина</a>
                                <div class="order__text">
                                    <p class=""><span class=" text_bold">{{ total_quantity }}</span> товаров</p>
                                    <p class="">На сумму <span class=" text_bold">{{ total_sum }} руб.</span></p>
                                </div>
                            </div>
                        </div>{% endblock %}

                {% endif %}

            </div>
        </div>
    </div>
    <div class="header__bot">
        <div class="wrapper">
            <ul class="header__tabs clearfix">
                <li>
                    <a href="#">
                        <div class="tab__img">
                            <img src="{% static 'img/tab_bouquets.png' %}" alt="bouquets">
                        </div>
                        <span class="tab__text">Букеты</span>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <div class="tab__img">
                            <img src="{% static 'img/tab_flowers.png' %}" alt="flowers">
                        </div>
                        <span class="tab__text">Цветы</span>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <div class="tab__img">
                            <img src="{% static 'img/tab_roses.png' %}" alt="roses">
                        </div>
                        <span class="tab__text">Розы</span>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <div class="tab__img">
                            <img src="{% static 'img/tab_compositions.png' %}" alt="compositions">
                        </div>
                        <span class="tab__text">Композиции</span>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <div class="tab__img">
                            <img src="{% static 'img/tab_gifts.png' %}" alt="gifts">
                        </div>
                        <span class="tab__text">Подарки</span>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <div class="tab__img">
                            <img src="{% static 'img/tab_weddings.png' %}" alt="weddings">
                        </div>
                        <span class="tab__text">Свадебные букеты</span>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</header>




{% block content %}

{% endblock %}



{% block pagination %}

{% endblock pagination %}
<footer class="main__footer">
    <div class="prefooter__background">
        <div class="prefooter">
            <div class="wrapper clearfix">
                <div class="prefooter__cols col">
                    <a href="#" class="prefooter__item">О магазине</a>
                    <a href="#" class="prefooter__item">Почему мы?</a>
                    <a href="#" class="prefooter__item">Отзывы</a>
                    <a href="#" class="prefooter__item">Скидки</a>
                </div>
                <div class="prefooter__cols col">
                    <a href="#" class="prefooter__item">Гарантии</a>
                    <a href="#" class="prefooter__item">Возврат денежных средств</a>
                    <a href="#" class="prefooter__item">Корпоративные букеты и подарки</a>
                </div>
                <div class="prefooter__cols col">
                    <a href="#" class="prefooter__item">Доставка</a>
                    <a href="#" class="prefooter__item">Доставка в праздничные дни</a>
                    <a href="#" class="prefooter__item">Спецпредложения к праздникам</a>
                </div>

            </div>
        </div>
    </div>
    <div class="footer__background">
        <div class="footer">
            <div class="wrapper clearfix">
                <div class="footer__contacts">
                    <a href="tel:83515672146" class="footer__phone">8 (351) <span class="text_bold">567 21 46</span></a><a
                        href="#" class="footer__mail">e-mail: buket@mail.ru</a>
                </div>
                <div class="footer__copyright">
                    <p>Служба доставки цветов &reg; 2016</p>
                </div>
            </div>
        </div>
    </div>
</footer>

<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/jquery-ui.min.js' %}"></script>
<script src="{% static 'js/lightslider.min.js' %}"></script>

<script src="{% static 'js/common.js' %}"></script>

</body>

</html>

shop/templates/basket.html
<!DOCTYPE html>
<html lang="ru">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

<body>
{% extends 'base_template.html' %}
{% block content %}

    <div class="orderpage">
    <div class="wrapper">

    <div class="pr__order-container">
        <div class="pr-order">
            <p class="unit__title"><span class="unit__num">1</span>Ваш заказ</p>
            <div class="pr-order__box">
                <div class="pr-order__table">
                    <div class="pr-order__head">
                        <p class="pr-order__element element__name">Наименование</p>
                        <p class="pr-order__element"></p>
                        <p class="pr-order__element element__price">Цена {{ good_price }}</p>
                        <p class="pr-order__element element__amount">Количество {{ quantity_goods }}</p>
                        <p class="pr-order__element element__sum">Сумма </p>
                        <p class="pr-order__element element__sum">Изменить </p>
                    </div>
                    {% for good, quantity, summ in goods %}
                        <div class="pr-order__item">
                            <div class="item_photo">
                                <a href="{% url 'shop:product-detail' good.id %}"><img src="{{ good.img_1.url }}" alt=""></a></div>
                            <div class="item__name"> <a href="{% url 'shop:product-detail' good.id %}"> {{ good.name }}</a></div>
                            <div class="item__price">{{ good.price }} руб.</div>
                            <div class="item__count">
                                <div class="order__quantity-container"><a href="#"
                                                                          class="order__quantity-button order__minus">-</a>
                                    <input type="text" value="{{ quantity }}" name="order__count" maxlength="4"
                                           class="order__count"><a
                                            href="#" class="order__quantity-button order__plus">+</a>
                                </div>
                            </div>
                            <div class="item__sum">{{ summ }} руб.</div>
                            <div class="item__edit">
                                <a href="{% url 'shop:del-good-from-basket' %}?remove=good_{{ good.id }}">Видалити</a>
                            </div>
                        </div>
                    {% endfor %}

                </div>
                <div class="pr-order__sum">
                    <p>Сумма:<span>{{ total_sum }} руб.</span></p>
                </div>
            </div>
        </div>
        <a href="{% url 'shop:product-order' %}" style="display: inline-block" class="order__button">Оформить заказ</a>
    </div>





{% endblock content %}
</body>
</html>

shop/templates/product_order.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends 'base_template.html' %}
{% block content %}
    <div class="pr__delivery">
                <div class="unit__title"><span class="unit__num">2</span>Доставка</div>
                <div class="checkbox-row recipient_wrap">
                    <div class="checkbox__container del-check">
                        <input type="radio" name="sendOption" value="sendPickup" id="sendPickup">
                        <label for="sendPickup">Самовывоз</label>
                    </div>
                    <div class="checkbox__container del-check">
                        <input type="radio" name="sendOption" value="sendOrder" id="sendOrder" checked>
                        <label for="sendOrder">Доставка</label>
                    </div>
                </div>


                <div class="pr__delivery-form send_client">
                    <form action="{% url 'shop:product-order' %}" method="post" class="clearfix">
                        <div class="delivery__form_wrap">
                            <div class="inputs-row">
                                <div class="inputs-row__title">Получатель:</div>
                                <div class="inputs_wrap">
                                    <input type="text" placeholder="Имя" name="name">
                                    <input type="text" placeholder="Телефон" name="phone">
                                </div>
                            </div>
                            <div class="inputs-row adress-row">
                                <div class="inputs-row__title">Адрес доставки:</div>
                                <div class="adress_cont">
                                    <div class="input-cont_wrap">
                                        <input type="text" placeholder="Город" name="city" class="option_field">
                                        <a href="" class="location_link"></a>
                                    </div>
                                    <input type="text" placeholder="ул. Советская, д. 62, кв. 3" name="adress">
                                </div>
                            </div>
                            <div class="inputs-row delivery__time-date">
                                <div class="inputs-row__title">Дата и время доставки:</div>
                                <div class="data-time_cont">
                                    <div class="input-cont_wrap">
                                        <input type="text" placeholder="08.03.16" name="data" class="option_field">
                                        <a href="#" class="pr__delivery__date"></a>
                                    </div>
                                    <div class="input-cont_wrap time-input">
                                        <input type="text" placeholder="00.00" name="time" class="option_field">
                                        <a href="#" class="pr__delivery__time"></a>
                                    </div>
                                    <div class="delivery__work-time">
                                        <span class="text__divide">* С 9.00 до 24.00 - 500 руб.</span>
                                        <span class="text__divide">Доставка в ночное время - 700 руб.</span>
                                    </div>
                                </div>
                            </div>
                            <div class="delivery__price">
                                <div class="price__delivery">
                                    <p class="price__name">Стоимость доставки составит:</p>
                                    <p class="price__sum">500 руб.</p>
                                </div>
                                <div class="pice__sum">
                                    <p class="price__name price__name_red">Итого:</p>
                                    <p class="price__sum price__sum_red">5 500 руб.</p>
                                </div>
                            </div>
                        </div>
                </div>
            </div>
            <div class="payment__section">
                <div class="payment__method">
                    <div class="unit__title"><span class="unit__num">3</span>Оплата</div>
                    <div class="payment__form">
                        <form action="" method="">
                            <div class="checkbox__container">
                                <input type="radio" value="reception" name="paymethod" id="reception">
                                <label for="reception">При получении</label>
                            </div>
                            <div class="checkbox__container">
                                <input type="radio" value="online" name="paymethod" id="online">
                                <label for="online">Онлайн</label>
                            </div>
                        </form>
                    </div>
                </div>
                <div class="payment__partners">
                    <div class="paypartners__item">
                        <img src="img/pay_webmoney.jpg" alt="">
                    </div>
                    <div class="paypartners__item">
                        <img src="img/pay_yandex.png" alt="">
                    </div>
                    <div class="paypartners__item">
                        <img src="img/pay_qivi.png" alt="">
                    </div>
                    <div class="paypartners__item">
                        <img src="img/pay_visa.png" alt="">
                    </div>
                </div>
            </div>
                    </form>
            </div>
                    <a href="{% url 'shop:homeview' %}" style="display: inline-block" class="order__button">Оформить заказ</a>

            </div>
{% endblock content %}
</body>
</html>