maki/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
import debug_toolbar
from maki import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/', include('shop.urls')),

]
if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [path(r"__debug__/", include(debug_toolbar.urls))]

urlpatterns += [
    path(r'accounts/', include('django.contrib.auth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

shop/urls.py
from django.conf.urls.static import static

from maki import settings
from . import views
from django.urls import include, path

app_name = 'shop'

urlpatterns = [path('homepage/', views.HomePage.as_view(), name='homeview'),
               path('product/<int:pk>', views.ProductDetail.as_view(), name='product-detail'),
               path('save_feedback/', views.save_feedback, name='save-feedback'),
               path('add_to_basket/<int:pk>', views.add_to_basket, name='add-to-basket'),
               path('add_to_basket_from_details/<int:pk>', views.add_to_basket_from_details, name='add-to-basket-from-details'),
               path('del_good_from_basket', views.del_good_from_basket, name='del-good-from-basket'),
               path('basket/', views.ProductBasket.as_view(), name='basket'),
               path('user_registration/', views.UserRegistration.as_view(), name='user-registration'),
               path('product_order/', views.ProductOrder.as_view(), name='product-order'),

               ]

shop/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
from django.forms import ModelForm


class Product(models.Model):
    choices = (
        ('bouquet', 'Bouquet'),
        ('present', 'Present'),
        ('composition', 'Composition'),)
    name = models.CharField(max_length=200)
    quantity = models.IntegerField()
    price = models.FloatField()
    description = models.TextField(max_length=1000)
    available = models.BooleanField(default=False)
    category = models.CharField(max_length=1, choices=choices, default='b')
    img_1 = models.ImageField(upload_to='products/img')
    img_2 = models.ImageField(upload_to='shop/static/img/products', blank=True)
    img_3 = models.ImageField(upload_to='shop/static/img/products', blank=True)
    img_4 = models.ImageField(upload_to='shop/static/img/products', blank=True)
    label = models.CharField(max_length=10,
                             choices=(
                                 ('item_new', 'n'), ('item_hit', 'h'), ('item_action', 'a'),
                                 (' ', '')),
                             default=' ')

    def __str__(self):
        return self.name


class Feedback(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    text = models.TextField(max_length=300)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    date = models.DateTimeField(auto_now=True)
    rating = models.IntegerField(choices=((1, 1), (2, 2), (3, 3), (4, 4), (5, 5)), default=5)

    class Meta:
        ordering = ['date']


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    order_date = models.DateTimeField(auto_now=True)
    payed = models.BooleanField(default=False)
    send = models.BooleanField(default=False)
    resive = models.BooleanField(default=False)
    order_sum = models.FloatField()
    recipient_phone = models.CharField(max_length=13)
    recipient_card = models.CharField(max_length=13)
    recipient_first_name = models.CharField(max_length=13)
    recipient_last_name = models.CharField(max_length=13)
    recipient_surname = models.CharField(max_length=13)
    recipient_city_address = models.CharField(max_length=13)
    recipient_local_address = models.CharField(max_length=13)
    add_free_message_card = models.BooleanField(max_length=13)
    free_message_card_text = models.TextField(max_length=100)
    delivery_datetime = models.DateTimeField()


class OrderForm(ModelForm):

    class Meta:
        model = Order
        exclude = ['order_date', 'send', 'payed']


class GoodsInOrder(models.Model):
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True, blank=True)
    good = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    payment = models.CharField(choices=(('online', 'online'), ('cash_on', 'cash_on')), max_length=15, default='cash_on')

shop/forms.py
from django import forms
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ValidationError

from django.contrib.auth.models import User

from shop.models import GoodsInOrder


class RegisterUserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    confirm_password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email']

    def valid_password(self):
        valid = self.changed_data
        if valid['password'] != valid['confirm_password']:
            raise ValidationError('Паролі не співпадають')
        return valid['password']


class AddToBasketFromDetails(forms.ModelForm):
    class Meta:
        model = GoodsInOrder
        fields = ['quantity', 'order']

shop/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.sites.shortcuts import get_current_site
from django.http import HttpResponseForbidden
from django.shortcuts import render, render_to_response, redirect
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.views import generic

from shop.forms import RegisterUserForm, AddToBasketFromDetails
from .models import *
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


# Create your views here.
class TopProductCookiesMixin:

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=None, **kwargs)
        quantity = 0
        sum = 0
        for item in self.request.session.keys():
            if 'good_' in item:
                q = int(self.request.session.get(item))
                id = int(item[5:])
                try:
                    good = Product.objects.get(pk=id)
                    price = good.price
                    quantity += q
                    sum += q * price
                except:
                    pass

        context['total_quantity'] = quantity
        context['sum'] = sum
        context['order'] = False
        return context


class HomePage(TopProductCookiesMixin, generic.ListView):
    model = Product
    paginate_by = 4

    def listing(self):
        product_list = Product.objects.all()
        paginator = Paginator(product_list, 4)  # Show 4 contacts per page

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(HomePage, self).get_context_data(**kwargs)
        quantity_goods = 0
        total_sum = 0
        for item in self.request.session.keys():
            if 'good_' in item:
                q = int(self.request.session.get(item))
                id_good = int(item[5:])
                try:
                    good = Product.objects.get(pk=id_good)
                    quantity_goods += q
                    total_sum += q * good.price
                except:
                    pass

        context['total_quantity'] = quantity_goods
        context['total_sum'] = total_sum
        return context


class ProductDetail(TopProductCookiesMixin, generic.DetailView):
    model = Product

    def get_context_data(self, *, object_list=None, **kwargs):
        if self.request.GET.get('order_quantity'):
            print("GEEET")
            self.request.session['good_' + str(self.kwargs['pk'])] = int(self.request.GET.get('order_quantity'))
        context = super().get_context_data(object_list=None, **kwargs)
        context['quantity'] = self.request.session.get('good_' + str(self.kwargs['pk']), 1)
        return context

    # def get_queryset(self):
    #     result = super().get_queryset()
    #     result2 = Product.objects.all()
    #     return result2


def add_to_basket_from_details(request, pk):
    print(request.GET.get('order_quantity'))
    good = 'good_' + str(pk)
    quantity = request.session.get(good, 0)
    # request.session[good] = quantity + value_quantity


def save_feedback(request):
    if request.POST:
        # print(request.POST)
        feedback = Feedback()
        feedback.user_id = int(request.POST['user_id'])
        feedback.product_id = int(request.POST['product_id'])
        feedback.text = request.POST['text']

        if not Feedback.objects.filter(text__contains=request.POST['text']):
            feedback.save()

        return redirect(to=request.POST['url'])
    else:
        redirect(to='/')


def add_to_basket(request, pk):
    good = 'good_' + str(pk)
    quantity = request.session.get(good, 0)
    request.session[good] = quantity + 1

    for item in request.session.keys():
        print(item, '=', request.session.get(item))
    return redirect(to='/shop/homepage/')


def del_good_from_basket(request):
    request.session.pop(request.GET.get('remove'))
    return redirect('shop:basket')


class ProductBasket(generic.TemplateView, TopProductCookiesMixin):
    template_name = 'basket.html'

    def get_context_data(self, **kwargs):

        context = super(ProductBasket, self).get_context_data(**kwargs)
        total_sum = 0
        goods = []

        for item in self.request.session.keys():
            if 'good_' not in item:
                continue
            quantity_goods = int(self.request.session.get(item))
            context['total_quantity'] = quantity_goods

            try:
                good = Product.objects.get(pk=int(item[5:]))
                summ = quantity_goods * good.price
                total_sum += summ
                goods.append((good, int(self.request.session.get(item)), summ))
            except:
                pass
        context['goods'] = goods
        context['total_sum'] = total_sum
        context['order'] = True
        return context


class ProductOrder(TopProductCookiesMixin, LoginRequiredMixin, generic.CreateView):
    template_name = 'product_order.html'
    model = Order
    form_class = OrderForm
    success_url = 'shop:product_list'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['order'] = True

        return context

    def form_valid(self, form):
        print(form.cleaned_data)

    def form_invalid(self, form):
        print("Form invalid")
        print(form.cleaned_data)

    # def save_to_database(self):


class UserRegistration(generic.CreateView):
    form_class = RegisterUserForm
    template_name = 'registration/user_registration.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return HttpResponseForbidden()

        return super(UserRegistration, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        # print('form valid')
        user = form.save(commit=False)
        user.set_password(form.cleaned_data['password'])
        user.save()
        # print("_______", user)
        # login(request=self.request, user=user)
        # print("_______222222", user)
        # current_site = get_current_site(self.request)
        # subject = 'Activation of your account'
        # message = render_to_string('blog/acc_activate_email.html', {'user': user,
        #                                                             'domain': current_site.domain,
        #                                                             'uid': urlsafe_base64_encode(
        #                                                                 force_bytes(user.pk)).decode(),
        #                                                             'token': account_activation_token.make_token(
        #                                                                 user)})
        # to_email = form.cleaned_data['email']
        #
        # email = EmailMessage(subject, message, to=[to_email])
        # email.send()
        # messages.success(self.request, 'Please confirm account by your e-mail.')

        return redirect(to='/shop/homepage/')

shop/templates/shop/product_list.html
<!DOCTYPE html>
<html lang="ru">
{% extends "base_template.html" %}
<head>
    <meta charset="UTF-8">



</head>
<body>
{% load static %}
{% block content %}
    <div class="content">
        <div class="wrapper clearfix">

            <div class="content__filters">
                <div class="filter clearfix">
                    <div class="button__container">
                        <a href="#" class="filter__btn">фильтр</a>
                    </div>
                    <div class="filter_wrap clearfix">
                        <p class="filter__title">Стоимость</p>
                        <div class="filter__value">
                            <div class="slider__container">
                                <div id="slider"></div>
                            </div>
                            <div class="clearfix">
                                <div class="slider__min-value">
                                    <input type="text" value="0" name="" id="amount" disabled>
                                    <label for="amount">руб.</label>
                                </div>
                                <div class="slider__max-value">
                                    <input type="text" value="5000" name="" id="amount1" disabled>
                                    <label for="amount1">руб.</label>
                                </div>
                            </div>
                        </div>
                        <div class="filter__product">
                            <p class="filter__title">Букеты с</p>
                            <form action="" method="" class="clearfix">
                                <div class="checkbox__container">
                                    <input type="checkbox" value="rose" name="check" id="rose">
                                    <label for="rose">Розами</label>
                                </div>
                                <div class="checkbox__container">
                                    <input type="checkbox" value="lily" name="check" id="lily">
                                    <label for="lily">Лилиями</label>
                                </div>
                                <div class="checkbox__container">
                                    <input type="checkbox" value="gerbera" name="check" id="gerbera">
                                    <label for="gerbera">Герберами</label>
                                </div>
                                <div class="checkbox__container">
                                    <input type="checkbox" value="peony" name="check" id="peony">
                                    <label for="peony">Пионами</label>
                                </div>
                                <div class="checkbox__container">
                                    <input type="checkbox" value="callas" name="check" id="callas">
                                    <label for="callas">Каллами</label>
                                </div>
                                <div class="checkbox__container">
                                    <input type="checkbox" value="iris" name="check" id="iris">
                                    <label for="iris">Ирисами</label>
                                </div>
                                <div class="checkbox__container">
                                    <input type="checkbox" value="orchids" name="check" id="orchids">
                                    <label for="orchids">Орхидеями</label>
                                </div>
                                <div class="checkbox__container">
                                    <input type="checkbox" value="carnations" name="check" id="carnations">
                                    <label for="carnations">Гвоздиками</label>
                                </div>
                                <div class="checkbox__container">
                                    <input type="checkbox" value="tulips" name="check" id="tulips">
                                    <label for="tulips">Тюльпанами</label>
                                </div>
                                <div class="checkbox__container">
                                    <input type="checkbox" value="daisies" name="check" id="daisies">
                                    <label for="daisies">Ромашкой</label>
                                </div>
                                <div class="checkbox__container">
                                    <input type="checkbox" value="chrysanthemum" name="check" id="chrysanthemum">
                                    <label for="chrysanthemum">Хризантемами</label>
                                </div>
                                <div class="checkbox__container">
                                    <input type="checkbox" value="alstroemeria" name="check" id="alstroemeria">
                                    <label for="alstroemeria">Альстромериями</label>
                                </div>
                                <div class="checkbox__container">
                                    <input type="checkbox" value="lisianthus" name="check" id="lisianthus">
                                    <label for="lisianthus">Лизиантусами</label>
                                </div>
                                <div class="checkbox__container">
                                    <input type="checkbox" value="exotic" name="check" id="exotic">
                                    <label for="exotic">Екзотическими цветами</label>
                                </div>
                            </form>
                        </div>
                        <div class="filter__whom">
                            <p class="filter__title">Кому</p>
                            <form action="" method="" class="clearfix">
                                <div class="checkbox__container">
                                    <input type="checkbox" value="male" name="check" id="male">
                                    <label for="male">Мужчина</label>
                                </div>
                                <div class="checkbox__container">
                                    <input type="checkbox" value="female" name="check" id="female">
                                    <label for="female">Женщина</label>
                                </div>
                                <div class="checkbox__container">
                                    <input type="checkbox" value="child" name="check" id="child">
                                    <label for="child">Ребенок</label>
                                </div>
                                <div class="checkbox__container">
                                    <input type="checkbox" value="family" name="check" id="family">
                                    <label for="family">Семья</label>
                                </div>
                                <div class="checkbox__container">
                                    <input type="checkbox" value="favorite" name="check" id="favorite">
                                    <label for="favorite">Любимой</label>
                                </div>
                                <div class="checkbox__container">
                                    <input type="checkbox" value="partners" name="check" id="partners">
                                    <label for="partners">Деловому партнеру</label>
                                </div>
                            </form>
                        </div>
                        <div class="filter__search">
                            <p class="filter__title">Поиск</p>
                            <label for="">
                                <input type="search" placeholder="Что вы ищите?" class="search__field"><a href="#"
                                                                                                          class="search__btn"></a>
                            </label>
                        </div>
                    </div>
                </div>
            </div>
            {% if product_list %}
                <div class="good">
                {% for good in product_list %}
                    <div class="goods__wrap clearfix">

                    <div class="goods__item {{ good.label }}">
                        <a href="{% url 'shop:product-detail' good.id %}">
                            <div class="goods__img">
                                <img src="{{ good.img_1.url }}" alt="{{ good.category }}">
                            </div>
                        </a>
                        <a class="goods__name" href="{% url 'shop:product-detail' good.id %}">{{ good.name }} </a>
                        <p class="goods__price">{{ good.price }} руб.</p>
                        <a href="{% url 'shop:add-to-basket' good.id %}" class="goods__btn">Заказать</a>
                    </div>
                {% endfor %}

            {% block pagination %}
                {% if is_paginated %}
                    <div class="goods__pages">
                        <ul>
                            {% if page_obj.has_previous %}
                                <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">Previous</a>
                            {% endif %}
                            <li><a class="pages_active"
                                   href="{{ request.path }}">{{ page_obj.number }}</a></li>
                            {% if page_obj.has_next %}
                                <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">Next</a>
                            {% endif %}

                        </ul>
                    </div>
                {% endif %}
            {% endblock pagination %}


            </div>
            {% endif %}


            </div>
        </div>
    </div>

    <div class="news">
        <div class="wrapper">
            <div class="news__head clearfix">
                <p class="section__title news__title">Новости</p>
                <a class="news__list" href="#">Все новости</a>
            </div>
            <div class="news__cols clearfix">
                <div class="col_x3">
                    <div class="news__item">
                        <div class="news__images">
                            <img src="{% static 'img/img_news-1.jpg' %}" alt="">
                            <a href="#" class="news__hover"></a>
                        </div>
                        <div class="news__content">
                            <p class="news__date">01.01.16</p>
                            <a href="#" class="news__text">С Новым годом 2016!</a>
                        </div>
                    </div>
                </div>
                <div class="col_x3">
                    <div class="news__item">
                        <div class="news__images">
                            <img src="{% static 'img/img_news-2.jpg' %}" alt="">
                            <a href="#" class="news__hover"></a>
                        </div>
                        <div class="news__content">
                            <p class="news__date">01.01.16</p>
                            <a href="#" class="news__text">Как украсить дом к Новому году?</a>
                        </div>
                    </div>
                </div>
                <div class="col_x3">
                    <div class="news__item">
                        <div class="news__images">
                            <img src="{% static 'img/img_news-3.jpg' %}" alt="">
                            <a href="#" class="news__hover"></a></div>
                        <div class="news__content">
                            <p class="news__date">01.01.16</p>
                            <a href="#" class="news__text">Розыгрыш новогоднего подарка</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


{% endblock content %}
</body>
</html>